config/routes.rb
Badgecraft::Application.routes.draw do
  resources :badge_assertions
  resources :badges
  resources :users

  get 'criteria/:id' => 'badges#criteria', as: 'criteria'

end

app/models/badge.rb
class Badge < ActiveRecord::Base
  mount_uploader :image, BadgeImageUploader

  def issuer
    "#{EasyConfig.app.host}/issuer.json"
  end

  def criteria_url
    #criteria_path
    "teste.com"
  end
end

app/models/badge_assertion.rb
class BadgeAssertion < ActiveRecord::Base
  belongs_to :badge
  belongs_to :user
end

app/models/criteria.rb
class Criteria < ActiveRecord::Base
  belongs_to :badge
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/badge_assertions_controller.rb
class BadgeAssertionsController < ApplicationController
  before_action :set_badge_assertion, only: [:show, :edit, :update, :destroy]

  # GET /badge_assertions
  def index
    @badge_assertions = BadgeAssertion.all
  end

  # GET /badge_assertions/1
  def show
  end

  # GET /badge_assertions/new
  def new
    @badge_assertion = BadgeAssertion.new
  end

  # GET /badge_assertions/1/edit
  def edit
  end

  # POST /badge_assertions
  def create
    @badge_assertion = BadgeAssertion.new(badge_assertion_params)

    if @badge_assertion.save
      redirect_to @badge_assertion, notice: 'Badge assertion was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /badge_assertions/1
  def update
    if @badge_assertion.update(badge_assertion_params)
      redirect_to @badge_assertion, notice: 'Badge assertion was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /badge_assertions/1
  def destroy
    @badge_assertion.destroy
    redirect_to badge_assertions_url, notice: 'Badge assertion was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge_assertion
      @badge_assertion = BadgeAssertion.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def badge_assertion_params
      params.require(:badge_assertion).permit(:badge_id, :user_id)
    end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: [:show, :edit, :update, :destroy]

  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(badge_params)

    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render action: 'show', status: :created, location: @badge }
      else
        format.html { render action: 'new' }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badges/1
  # PATCH/PUT /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge.destroy
    respond_to do |format|
      format.html { redirect_to badges_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def badge_params
      params.require(:badge).permit(:name, :description, :criteria, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/badge_assertions_helper.rb
module BadgeAssertionsHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/issuer_helper.rb
module IssuerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/badge_assertions/_form.html.erb
<%= form_for(@badge_assertion) do |f| %>
  <% if @badge_assertion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@badge_assertion.errors.count, "error") %> prohibited this badge_assertion from being saved:</h2>

      <ul>
      <% @badge_assertion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :badge_id %><br>
    <%= f.text_field :badge_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/badge_assertions/edit.html.erb
<h1>Editing badge_assertion</h1>

<%= render 'form' %>

<%= link_to 'Show', @badge_assertion %> |
<%= link_to 'Back', badge_assertions_path %>

app/views/badge_assertions/index.html.erb
<h1>Listing badge_assertions</h1>

<table>
  <thead>
    <tr>
      <th>Badge</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @badge_assertions.each do |badge_assertion| %>
      <tr>
        <td><%= badge_assertion.badge %></td>
        <td><%= badge_assertion.user %></td>
        <td><%= link_to 'Show', badge_assertion %></td>
        <td><%= link_to 'Edit', edit_badge_assertion_path(badge_assertion) %></td>
        <td><%= link_to 'Destroy', badge_assertion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Badge assertion', new_badge_assertion_path %>

app/views/badge_assertions/new.html.erb
<h1>New badge_assertion</h1>

<%= render 'form' %>

<%= link_to 'Back', badge_assertions_path %>

app/views/badge_assertions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Badge:</strong>
  <%= @badge_assertion.badge %>
</p>

<p>
  <strong>User:</strong>
  <%= @badge_assertion.user %>
</p>

<%= javascript_include_tag "https://backpack.openbadges.org/issuer.js" %>
<button id="issue">Send!</button>
<script>
  $('#issue').click(function() {
    OpenBadges.issue(["<%= badge_assertion_url(@badge_assertion, format: :json) %>"], function(errors, successes) {
      console.log(errors);
      console.log(successes);
      alert('Foi!');
    });
  });
</script>

<%= link_to 'Edit', edit_badge_assertion_path(@badge_assertion) %> |
<%= link_to 'Back', badge_assertions_path %>

app/views/badge_assertions/show.json.erb
{
  "uid": "<%= @badge_assertion.id %>",
  "recipient": {
    "type": "email",
    "hashed": false,
    "identity": "<%= @badge_assertion.user.email %>"
  },
  "issuedOn": "<%= @badge_assertion.created_at.iso8601 %>",
  "badge": "<%= badge_url(@badge_assertion.badge, format: :json) %>",
  "verify": {
    "type": "hosted",
    "url": "<%= badge_assertion_url(@badge_assertion, format: :json) %>"
  }
}

app/views/badges/_form.html.erb
<%= form_for(@badge, :html => { :multipart => true }) do |f| %>
  <% if @badge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
      <% @badge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :criteria %>
    <%= f.text_field :criteria %>
  </div>
  <div class="field">
    <%= f.hidden_field(:image_cache) %>
    <%= f.file_field(:image) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/badges/edit.html.erb
<h1>Editing badge</h1>

<%= render 'form' %>

<%= link_to 'Show', @badge %> |
<%= link_to 'Back', badges_path %>

app/views/badges/index.html.erb
<h1>Listing badges</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @badges.each do |badge| %>
      <tr>
        <td><%= cl_image_tag badge.image, :width => 250, :height => 250 %></td>
        <td><%= badge.name %></td>
        <td><%= link_to 'Show', badge %></td>
        <td><%= link_to 'Edit', edit_badge_path(badge) %></td>
        <td><%= link_to 'Destroy', badge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Badge', new_badge_path %>

app/views/badges/new.html.erb
<h1>New badge</h1>

<%= render 'form' %>

<%= link_to 'Back', badges_path %>

app/views/badges/show.html.erb
<p id="notice"><%= notice %></p>
<div><%= @badge.name %></div>
<div><%= cl_image_tag @badge.image, :width => 250, :height => 250 %></div>

<%= link_to 'Edit', edit_badge_path(@badge) %> |
<%= link_to 'Back', badges_path %>

app/views/badges/show.json.erb
{
  "name": "<%= @badge.name %>",
  "description": "<%= @badge.description %>",
  "image": "<%= @badge.image.url %>",
  "criteria": "<%= @badge.criteria %>",
  "issuer": "<%= @badge.issuer %>"
}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Badgecraft</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
        <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
        <%= csrf_meta_tags %>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="skin-black">
        <!-- header logo: style can be found in header.less -->
        <header class="header">
            <a href="../index.html" class="logo">
                <!-- Add the class icon to your logo image or logo icon to add the margining -->
                Badgecraft Abril
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
            </nav>
        </header>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="left-side sidebar-offcanvas">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">
                    <!-- Sidebar user panel -->
                    <div class="user-panel">
                        <div class="pull-left image">
                            <img src="../img/avatar3.png" class="img-circle" alt="User Image" />
                        </div>
                        <div class="pull-left info">
                            <p>Hello, Diogo</p>
                        </div>
                    </div>
                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <ul class="sidebar-menu">
                        <li class="active">
                            <a href="/badges">
                                <i class="fa fa-dashboard"></i> <span>Badges</span>
                            </a>
                        </li>
                        <li class="active">
                            <a href="/users">
                                <i class="fa fa-dashboard"></i> <span>Usuários</span>
                            </a>
                        </li>
                        <li class="active">
                            <a href="/badge_assertions">
                                <i class="fa fa-dashboard"></i> <span>Entregar uma badge</span>
                            </a>
                        </li>
                    </ul>
                </section>
                <!-- /.sidebar -->
            </aside>

            <!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side">
                <!-- Content Header (Page header) -->
                <!--
                <section class="content-header">
                    <h1>
                        Blank page
                        <small>Control panel</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li class="active">Blank page</li>
                    </ol>
                </section>
                -->
                <!-- Main content -->
                <section class="content">
                  <%= yield %>
                </section><!-- /.content -->
            </aside><!-- /.right-side -->
        </div><!-- ./wrapper -->
    </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user, :html => { :multipart => true }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New user', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div><%= @user.name %></div>
<div><%= @user.email %></div>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>